POST http://localhost:3000/api/user/authenticate 
Content-Type: application/json

{
    "email" : "logesh@gmail.com",
    "password" : "logesh"
}

###
GET http://localhost:3000/api/fruit/name
Content-Type: application/json

{
    "productname" : "apple"
}

###
POST http://localhost:3000/api/user/personalinfo
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGlkIjoibG9nZXNoQGdtYWlsLmNvbSIsImlhdCI6MTYwMDA5MjUxOX0.h8raLsBa7GhiBuwDL0IzfXrEbKbf5rF8XUp39Y67nIo

Content-Type: application/json

{
    "email" : "logesh@gmail.com",
    "mobile" : "9245849107",
    "doorno" : "10",
    "street" : "nethaji street",
    "district" : "Dindigul"
}

###
POST http://localhost:3000/api/user/sellerlist
Content-Type: application/json

{
    "email" : "ramesh@gmail.com"
}

###
GET http://localhost:3000/api/auth
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbGlkIjoibG9nZXNoQGdtYWlsLmNvbSIsImlhdCI6MTYwMDA5MjUxOX0.h8raLsBa7GhiBuwDL0IzfXrEbKbf5rF8XUp39Y67nIo

